const SET_DAYS = 'SET_DAYS';
const START_DAYS_LOADING = 'START_DAYS_LOADING';
const SET_DAYS_ERROR = 'SET_DAYS_ERROR';
const RESET_DAYS_ERROR = 'RESET_DAYS_ERROR';
const ADD_DAY = 'ADD_DAY';
const EDIT_DAY = 'EDIT_DAY';

const SET_YEARS = 'SET_YEARS';
const START_YEARS_LOADING = 'START_YEARS_LOADING';
const SET_YEARS_ERROR = 'SET_YEARS_ERROR';
const RESET_YEARS_ERROR = 'RESET_YEARS_ERROR';
const ADD_YEAR = 'ADD_YEAR';

const SET_SETTINGS = 'SET_SETTINGS';

export default {
  SET_DAYS,
  START_DAYS_LOADING,
  SET_DAYS_ERROR,
  RESET_DAYS_ERROR,
  ADD_DAY,
  EDIT_DAY,
  SET_YEARS,
  START_YEARS_LOADING,
  SET_YEARS_ERROR,
  RESET_YEARS_ERROR,
  ADD_YEAR,
  SET_SETTINGS,
};