const SET_DAYS = 'SET_DAYS';
const START_DAYS_LOADING = 'START_DAYS_LOADING';
const SET_DAYS_ERROR = 'SET_DAYS_ERROR';
const RESET_DAYS_ERROR = 'RESET_DAYS_ERROR';
const ADD_DAY = 'ADD_DAY';
const EDIT_DAY = 'EDIT_DAY';

export default {
  SET_DAYS,
  START_DAYS_LOADING,
  SET_DAYS_ERROR,
  RESET_DAYS_ERROR,
  ADD_DAY,
  EDIT_DAY,
};